[build]
  command = "migrate:deploy" 
  publish = "dist"  

[[redirects]]
  from = "/*"  
  to = "/index.html"  # Redirecionar para o arquivo index.html para aplicativos de página única (SPA)

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[build.environment]
  DATABASE_URL = "postgresql://postgres:lL6yUMjEW9wMTegyM4Ef@containers-us-west-43.railway.app:6015/railway"
  PGHOST = "containers-us-west-43.railway.app"
  PGUSER = "postgres"
  PGPASSWORD = "lL6yUMjEW9wMTegyM4Ef"
  PGDATABASE = "railway"
  PGPORT = "6015"
